### ISSUE TITLE
To Chronos

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#17]
:DELETED:

**Comment by Raven-Quest** [comment]
hee... I can read this ya know LOL :P

**Comment by SpiceyWolf** [comment]
Yes... im not trying to trash talk you either, im just simply making the point that since the last encounter ive had with you, I dont find it likely you would have the skill set to implement my stuff which requires a decent understanding of both classes and networking. Youd have to have learned quite alot in a short amount of time and id imagine you would have much better things to do than research those specific topics ;P

**Comment by Chronos-92** [comment]
I'm aware of there being many problems. I had a bunch of ideas written down on how to tackle some of them but Damian seems reluctant on changing to a more modern style of coding. (hence a lot of my work on the Monogame rendering methods just being almost direct copy/pastes and methods made to resemble his old methods on the outside as much as possible) I just don't feel comfortable rewriting such a major part of the engine if he's not going to be able to work with it. 

I'm also recently employed again, so I do not have nearly as much spare time to work on this sort of stuff anymore aside from a few mornings on weekends where my fiancé isn't awake yet. It'd be an interesting project to use a different method for networking for sure, but I can currently not say I have the time to actually set aside for such a project. I barely have time to work on my own projects as it is, haha.

We'll see, I might take this up at some point! But at the moment I'm not in a position to do so.

**Comment by Damian666** [comment]
nah I know man, just messing around lol 

and that what chronos posted is the mayor problem xD

**Comment by SpiceyWolf** [comment]
lol you wouldnt really find it a new method of networking if you are familiar with vb6 era... my code follows a strict pattern to code in EO style as well... as far as networking goes the way an engine of this style requires, thats the most optimal way to do it. The code would look almost exactly as it did (from the end where ur using it, not all the backend that powers it) to the vb6 code :D

**Comment by Raven-Quest** [comment]
and that's why I like your coding more then chronos his style, I mean, I know he tries to learn me stuff, but I to old for that shit xD

I did pick up on the path.combine etc though lolz

**Comment by Chronos-92** [comment]
I can't help it I enjoy my C# gibberish. :P

**Comment by Raven-Quest** [comment]
I know lol

**Comment by SpiceyWolf** [comment]
haha all my stuff is in c# too brother xD i approached the problem which is why my efforts dropped off quickly is that no matter how much you modify or rewrite crap... ur still gunna redo parts you already did and mix urself up and its a slow painful process to go somewhere and if you have the understanding and patience to do all that, you are more than likely capable of just writing one from scratch thats better...

Im doing that on my own terms for a game thats in EO on steam to try to survive atm.. not sure if i really care tbh to further that development into my own games, im pretty lustful on the idea of absorbing low level knowlege of Mac/Linux/Windows and just making a new ".net" style core library for the D language... then building some games from there.

**Comment by SpiceyWolf** [comment]
All in all, id recommend just avoiding MonoGame even for you chronos if you can put up with it... 3.2 was their last uhh mostly working version, its feature based satisfied the majority of its fanbase and they just needed to refine it but then they started redoing stuff and breaking opengl and all sorts of other features in favor of directx(wtf was the point of remaking xna that wasnt supposed to be xna, to turn it into a wrapper happy xna that cant even meet the performance of xna) and then they started jumping everywhere breaking the majority of features, and well breaking more as they fixed others. Its a real mess its not worth even playing with till they got it totally figured out which isnt gunna be till somewhere around a 4.0 or 5.0.

**Comment by Raven-Quest** [comment]
well, I like to think orion is a bit better then eo personally lol

**Comment by SpiceyWolf** [comment]
Well it is design-wise from the work you both (and other people before i was around that seem to have participated) have put in.. Performance wise and stability wise, it wavers between whether orion or EO is better depending on the specific feature.

**Comment by Raven-Quest** [comment]
true... but its not vb6 atleast xD

**Comment by Chronos-92** [comment]
I honestly -could- make one myself, if I had the drive and patience. Heck I have some basic designs written down on paper and some demos for things I want to use ready to go. (server plugins based on event handlers!) It's just actually writing it that's the hard part.

And yeah, I've noticed MonoGame has been a major pain. But so has SFML to me, as it will just randomly not work on systems where MonoGame works, albeit with a more painful process to force it to work programmatically.

As for which is better between EO and Orion, I'd say both are about equally shiet. Let's be honest there, all the core flaws that EO had are pushed through in Orion and very little has been fixed while it has been expanded upon. Featurewise, Orion would win but it does come at a cost with it being much more complex to try and maintain.

**Comment by Raven-Quest** [comment]
it is a carbon copy off eo, so yes, I agree on that sigh...

**Comment by SpiceyWolf** [comment]
If you guys are goin the miles to just fix orion and make it great, the idea to follow, stick with SFML cause it is the most stable and up to date library that .net has even today which really sucks... 

Further from that, use whatever up to date network and IO functionality im making as it will kick ass versus whatever else, i am a neat freak and performance hungry muther fcker xD btw that ini stuff can be replaced to XML serialized classes with my IO stuff... when i get the updates..

Outside of that, just optimize the existing code there... clean up garbage code, minimize the code needed to perform the task and youll be fine. A majority of your bugs will go away with that simple task in mind.

**Comment by Raven-Quest** [comment]
ini files are out mate, I removed it :)

**Comment by SpiceyWolf** [comment]
Chronos can you be specific about sfml not working on systems where monogame does? aside from game consoles you have to pay for access and mobile devices, sfml should be fine i kept in mind to make sure they work.

**Comment by Chronos-92** [comment]
I never understood the usage of your IO module, it looks like ass where a simple extension such as this would suffice:
> public static String ToXml<T>(this T input) {
> 		using (var writer = new StringWriter()) {
> 			var serializer = new XmlSerializer(input.GetType());
> 			serializer.Serialize(writer, input);
> 			return writer.ToString();
> 		}
> 	}
> 	public static T FromXml<T>(this string objectData) {
> 		return (T)FromXml(objectData, typeof(T));
> 	}
> 	private static object FromXml(this string objectData, Type type) {
> 		var serializer = new XmlSerializer(type);
> 		using (TextReader reader = new StringReader(objectData)) {
> 			return serializer.Deserialize(reader);
> 		}
> 	}

And Damian, the way you do Xml is the same as Ini files. Which is god awful, just serialize a darn class. :P 

As for which parts don't work on SFML, I've noticed that on random machines SFML will simply refuse to start at all. Especially older machines which is odd as even when I use the same version of OpenGl in MonoGame it'll function just fine. (Mind you, this has been from roughly two years ago and I've dreaded using SFML since after having to tear it out of my project and rewriting it with another library to get it to work on like half my user's PCs.) It might work fine now, I just don't have the userbase to test this on.

EDIT: For some reason all formatting is lost whenever I enter code or blockquote markdown, what's up with that GitHub?

**Comment by SpiceyWolf** [comment]
what made EO shit was security flaws due to editors and game client being accessible with open source via eclipse website for anyone to brute their way in, and obviously proper security not concidered on all levels while doing so... as well as the methods for IO and networking not being absolutely optimized... the new Save/Load system i gave orion improved IO speed by MILES, that shit went from minutes to seconds and with a network swap i meen aside from small details like not all features being developed with dynamic growth in mind which isnt the end of the world for even newby coders, the rest isnt all that bad however even with good network, the 1client/1server model will NEVER produce mmo games.

**Comment by Raven-Quest** [comment]
atleast mine does not use brackets chronos xD

**Comment by Chronos-92** [comment]
Eh, that extension compiled would just turn into Options.ToXml(). No brackets there. ;)

**Comment by SpiceyWolf** [comment]
yeah the xml had problems before i wrote that when i was first learning ANYTHING about xml and its only up to date in my latest library... as are alot of updates xD have you been checkin out my repo bic boii? XD and that was another issue, of specificly sfml 2.1, some older machines dont like the GL 2.2 and 2.3 used, like my buddy HAD to use 2.1 in order for it to do anything on his pc... which in context was based on windows, i hope you are refering to the same xD sometimes can be driver support not liking the specific version sfml is using...

**Comment by SpiceyWolf** [comment]
oshit u were talking about his >.> yeah mine is about the same thougn x-x got confused, my irl name is damien too >: P

**Comment by Raven-Quest** [comment]
lolol

he is always nagging on me man, you should see the shit I get over at agd xD

**Comment by Chronos-92** [comment]
That's because it pains me to see some of the things you write, they're so.. 1995. 👎

**Comment by Raven-Quest** [comment]
well, I'm even older, deal with it :P

**Comment by SpiceyWolf** [comment]
btw... if u havent looked, please dont look at my repos o-o im ashamed of my previous work xD i only keep it up still in case i fck something up in my offline work and i need a reference... itll be gone soon enough >: P

**Comment by SpiceyWolf** [comment]
some of the things who rights? 666? XD what u got against 1995 boii?!

**Comment by Raven-Quest** [comment]
yeah me lol

**Comment by SpiceyWolf** [comment]
there ... shhhh look at this:
https://github.com/SpiceyWolf/ColorTool
and the sfml.portable repos... refrain from the IO and net repos :O they are scary chit.

**Comment by Chronos-92** [comment]
Eh, I have a bunch of stuff I'm not proud of either. But I keep most of my things in a private repo on my own hosts. But then I also write things cleanly like this: https://source.vanharberden.eu/silvester/zoneminder-api/tree/master (Which I think actually looks fairly clean!) It really depends on what I'm writing, for who and how much experience I have with writing said thing.

And I was talking to @Damian666 , not @SpiceyWolf about the painfully written code.

**Comment by SpiceyWolf** [comment]
i meen... hory, the net for one is buggy as shit i think i JUST implemented a ringed-buffer last update... probably not... but it used to have an issue with packet spamming causing packets to drop... then overbuffers... and i wasnt quite sure how the concept of the ringbuffer was supposed to work when i first implemented that xD

And for the IO... mai gawd the redundancy man... it was horrid.

**Comment by SpiceyWolf** [comment]
use a different year ;~; 1995 is muh year man... its MAH YEAR! i wouldnt be here without it x-x

**Comment by SpiceyWolf** [comment]
no seriously though i legit would not be here without it O_O

**Comment by Raven-Quest** [comment]
well, nice or not, atleast I'm having fun lol :P

**Comment by SpiceyWolf** [comment]
I wish i could still have fun coding ;~; i meen i probably would if it was D, but i got this job to do, then get a real boring job... then get a house... then see my gf after 5 years... ive quite lost the interest in programming really x-x

**Comment by Chronos-92** [comment]
Programming has always been a hobby for me. Though I do quite enjoy it, I mainly enjoy fixing problems though, it's really boring making new systems.

**Comment by SpiceyWolf** [comment]
its like super cool when ur just playing with it, but then u get serious and try to build cool shit and u just wanna just put ur head in a wall and call it a day :D

**Comment by Raven-Quest** [comment]
bummer bro..

its nice to only have fun...

**Comment by SpiceyWolf** [comment]
Ey if you really like an adventure chronos, get into compiled languages, its stomache churning to get used to setting projects up and compile scripts and all that... it still makes me sick just thinking of them x-x but its nice not to have all the bloatware and bullshit these non compiled langs have... and the security of ur code is just a beauty in of its self... hell java and .net ur code is pretty much just given away and u can only rely on a license and the discretion of the government a potential theif has to protect ur chit..

**Comment by SpiceyWolf** [comment]
ey chronos xD since u seem old enough to make a comment about code style being as old as i am, if you dont mind me asking... just how old are you?!

**Comment by Chronos-92** [comment]
I've dabbled in C/C++ once or twice, but I always felt it was too much of a hassle to set things up to get it to work.

And I'm not very old, I'm only 24. But I had some very.. VERY strict guidance on working in .Net for a few years. Hahaha.

**Comment by SpiceyWolf** [comment]
damn... im almost 22 o-o and i can say the same about .net >_> though ive learned to hate it so much for all of its flaws... from purposely wasteful memory, poor language design, and refusal to fix issues in their shit, to security flaws like no other and just the clr being total ass... its still more stable and powerful than java, but these fake languages will always leave a bad taste in my mouth xD

**Comment by SpiceyWolf** [comment]
btw, if ur fuckin with C++, i dont blame you for disliking it hehe... C feels too limited for me even though its the superior language of any programmers options, that just short under assembly(but the difficulty curve on assembly far outweighs the benefit let alone if you can even UTILIZE the benefits) but C++ is just fuckin broken and because they refuse to lose backward compatibility to older levels of C++ that guarentees the langauge stays broke. Thats why ive been fangirling(not literally im male) over D cause its what C++ would be if they got their shit together <3

**Comment by SpiceyWolf** [comment]
OH btw... about my new IO stuff, i got encryption in there now :D it contains just some general string encryption, and then i got a method for Keypairs, cant remember if it was symetric or asymetric cause depending where i went the definition kept changing >_> its the one where u get a public and private key... public can only encrypt but u have to have private to unencrypt... and it uses a rather large definition so no one will be crackin that bitch >: P

**Comment by Chronos-92** [comment]
I might look into D at some point, from the snippets I'm seeing it looks fairly clean and simple. Currently dabbling in Node.Js for a webbased application though.

**Comment by SpiceyWolf** [comment]
OH if you do get interested in D, on that compiler shit, (gotta love this one) u get to take near as big a damn shortcut as u do with .net if you use Xamarin Studio 1.10.x editions... They got a lang binding for it so it generates compiler scripts and all that its as fairly straightforward as .net is when it comes down to it i promise, the ONLY thing that is still a pain in the ass, is linking libraries and shit... 

Though if you know how that is done in C or C++... its the same exact way, it took me a while to figure that one out xD

**Comment by SpiceyWolf** [comment]
whats the matter 666? convo get too.... 

...

"Spicy" for ya? XD

**Comment by Chronos-92** [comment]
He's probably confused, although we -are- using this as a chatbox while it's definitely not. lol

**Comment by SpiceyWolf** [comment]
lmfao they shouldnt have made it autoupdate without refreshing the page if they didnt want it to be used that way... its githubs fault xD

**Comment by Chronos-92** [comment]
D looks a lot like C# does but without the convenience of the .Net framework and its bazillions of classes to use at your leisure. Shouldn't be too hard to switch over, assuming I can actually find or write libs to do the standard stuff.

**Comment by SpiceyWolf** [comment]
yeah... theres loads of alternative frameworks too... i intend to recreate essentially the .net framework in there when i finish my shit im working on now

i spent a good while learning raw sockets in linux and windows, as well as threading, and OpenGL... so if i do everything based on those, itll be totally cross platform compatible and ultimately the highest performance possible :D i dont intend to go wrapper happy like .net does though -.- .net uses like the CORE os libs, which are sometimes wrappers themselves over other core os libs xD and then .net wraps that, and some of .net wraps .net that wraps that and even sometimes yet ANOTHER .net wrapping that... its a mess, i wanna have everything in D just like .net but without all the wrapping its just D over the core OS period. No layers of BS it removes possibility of buggy code, and offers highest performance ull possibly get...

**Comment by SpiceyWolf** [comment]
but yeah its pretty damn similar to C#, i converted an entire Q-bert style game i made in .net with SFML to D in just 2 days with honestly not the largest code changes...

**Comment by SpiceyWolf** [comment]
Only downside is yknow no WinForms... but there are graphical frameworks like GTK that even MonoDevelop/Xamarin has that there form designers for C++ to use(ultimately meening u can use them for D too) if you are into that... theres also if ur fine coding by hand still some SFML Ui libs for D in fact one of the IDE's for D is written using one xD

**Comment by SpiceyWolf** [comment]
Well hey, if either of you have skype feel free to add me - SpiceyWolf.ArchaicSoft

Ima hop out of here for a while, been up all night wanna catch a couple dbz episodes (i only recently started the series and finished dragon ball a few weeks ago) and then catch some unconscious delusions xD

**Comment by SpiceyWolf** [comment]
lol

**Comment by Raven-Quest** [comment]
📦 
no need to keep this open lolz

**Comment by ParchmentWolf** [comment]
those were accidental while i was spacing out xD
