### ISSUE TITLE
SFML notification

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#18]
:DELETED:

**Comment by SpiceyWolf** [comment]
well chit, realized another dilema here... i gotta figure out how to get back into my nuget to update all this chit xD

**Comment by Raven-Quest** [comment]
dude... xD

**Comment by Raven-Quest** [comment]
also, your welcome to add that speed up thingy real quick if you like :)

**Comment by SpiceyWolf** [comment]
yeaaaaahh... im not putting up a 2.4... it is incredibly broken... i had to run a bunch of stuff, music systems like half missing, some of the types like vectors are broken in certain systems... sprite doesnt work properly, like the draw function works but shit like getting specific rect's on it just ... no they arent working right xD Not sure if its just broken CSFML files, or what but even the guy working on it said he had to make some pretty chitty workarounds to use debug version of the dll (which meens they separated the debugging functions from the main dll)

**Comment by Raven-Quest** [comment]
awww thats to bad :/

**Comment by SpiceyWolf** [comment]
also ill put the mod on the client tomorrow.

**Comment by SpiceyWolf** [comment]
if u want the editor stuff done ull have to get around to that later... its pretty simple though and takes alot of the checking code away that was in orion to make sure detection inside the window properly would not be needed too :D

**Comment by Raven-Quest** [comment]
so... client mod? lol, forgot about it huh :P

**Comment by SpiceyWolf** [comment]
ochit... yup ill get to it right now hold on...

**Comment by Raven-Quest** [comment]
xd

**Comment by SpiceyWolf** [comment]
lol tbh i slept most of the day, woke up got into an argument with my grandma then started watching dbz >.> so im dling the source right now ill upload it over my repo and u can merge the changes

**Comment by Raven-Quest** [comment]
you still have access mate, just push it lol

**Comment by SpiceyWolf** [comment]
ik

**Comment by SpiceyWolf** [comment]
Ok so i uploaded it... Just wanna state for some reason i cant compile the client, not sure if its just a bug with my shiz(probably is because i cant use MSBuild for some reason so im use MonoCompiler) BUT... The render/loop separation should be good to go. 

Only thing im not sure if is implemented properly which im confident you could easily fix is the thing that will SHOW loop count... the frame limit should be about 70 or below... depending on how accurate the machine running the client's tick count is... or rather how stable... but the loop count should be MILES faster meening all your chit should be processing WELL before the game actually draws stuff so it should be TOTALLY accurate.

So if you have any trouble, i tried to put a separate command for the lps to draw, so if u do /lps it SHOULD if i implemented correctly show u a loop count which should run anywhere from 400 to 700k loops a second :D

**Comment by Raven-Quest** [comment]
kk, ill check it out :)

**Comment by SpiceyWolf** [comment]
The major problem why u didnt wanna use SFML's frame limiter is because thats not just a frame limiter, its an application limiter which can cause all sorts of issues with processing data and the speed of ur program to accurately handle chit the way u want... so if u limit on your own terms independant of the games loops, then u can receive MANY more packets, process waaaay more data like animations and all that chit and u wont even see a dent in the game on the visual level like before :D 

This problem would actually cause you to drop packets if they were sending faster than the client could receive them say if the game was lagging from heavy graphical work then ud just drop packets... thats kinda not okay xD but this shouold fix all of that and receive all packets independant of visual lag :P

**Comment by Raven-Quest** [comment]
very nice, I did not know that :))

**Comment by SpiceyWolf** [comment]
I figured it was worth pointing out as i noticed the comment in there about processing input and walking before rendering or it just wouldnt take place xD That will never be a problem again with this change :D
If you find the program starts taking too much cpu, u can also put a lps limiter similar to rendercount one that way it goes straight to the doevents/sleep system.

**Comment by Raven-Quest** [comment]
around 6% cpu, should be fine :P

**Comment by SpiceyWolf** [comment]
lol so have you gotten to see if the lps counter works? also whats ur fps runnin with that?

**Comment by Raven-Quest** [comment]
ive just put the lps in the fps string, seems to run the same so, fuck it lol

it says FPS:65 but its actually the lps, meh, looks fine xD

**Comment by SpiceyWolf** [comment]
if u have to just tag it on the end of the fps counter label and make the fps show... (in the case i didnt make the lps activate properly)

**Comment by SpiceyWolf** [comment]
hmm if its not running separately then there might be more chit putting limiters in the game loop... i dont have time to look over all that though :/ ud have to play with those urself and figure out how to make it stop limiting on lps... could maybe be the synclock?

**Comment by Raven-Quest** [comment]
it showed higher lps then fps, so its separate :)

no worry, its fine

**Comment by SpiceyWolf** [comment]
ahh... then if its still fairly low lps just play with some other chit in the loop (I meen if/when u need more performance back) just remember, having them separate meens you can put ALOT more strain on the engine both in gfx AND in data handling

**Comment by Raven-Quest** [comment]
65 seems fine to me man :)

**Comment by Raven-Quest** [comment]
I do notice a slight stutter when I walk though...

anything to make it more fluid?

**Comment by SpiceyWolf** [comment]
can u be more specific about the issue?

**Comment by SpiceyWolf** [comment]
what exactly is the fps at?

**Comment by Raven-Quest** [comment]
its almost as if the player char has the jeebeez xD

**Comment by Raven-Quest** [comment]
65 lps, fps 30 or so

**Comment by SpiceyWolf** [comment]
hmm...
either the movement handler is going too fast or the frames just need to be upped a little... try making the number for rendercount smaller like around 16 or so and see if that helps... if not ull have to change the time on walk timer possibly...

**Comment by Raven-Quest** [comment]
ill check it tonight, have to get to work :)

thanx bro!

**Comment by SpiceyWolf** [comment]
good god... take the do events out of that last section too (at the end of the synclock) every time you call do events you eat a chit ton of performance... and ur basicly calling it twice in a row for no reaosn at all xD

**Comment by SpiceyWolf** [comment]
in fact that do events just under the rendercount code i added should be inside of that rendercount block(just before the rendercount = tick + 32)

You only need to call DoEvents to update visual stuff... and being that the only time ur visual stuff updates is on the rendercount anyway, thats the only time it needs called... it doesnt need called every single loop...

Do that, your lps may jump way the hell up XD

**Comment by Raven-Quest** [comment]
nope, if I do that, it wont load lolz

**Comment by SpiceyWolf** [comment]
do what specificly? and what wont load?

**Comment by Raven-Quest** [comment]
move that do events up, duh xD

it wont even load the gfx when I start the client P

**Comment by Raven-Quest** [comment]
i made it 16 btw, now the jerkiness is much less

**Comment by SpiceyWolf** [comment]
hmm... well u still shouldnt need 2 doevents like that... if u have to have them then theres a bigger issue that needs fixed and some chit reordered in there.

**Comment by Raven-Quest** [comment]
i did remove the one above it, that seems to be fine :)

**Comment by SpiceyWolf** [comment]
Also when you say moved do events up, you do meen into the rendercount block i added correct?

**Comment by Raven-Quest** [comment]
yes

**Comment by Raven-Quest** [comment]
hee spicey, I was wondering if you have any examples of a lightning system?

I have basic lights, but I cant get them to accept colors etc..

its only the same color as the damn file it loads xD

**Comment by SpiceyWolf** [comment]
The color system in sfml is very wonky... its kinda like changing color balance in gimp or something...  so youd either have to generate ur own particle system by hand using pixels with specified color for the LITERAL light source with a semi transparent white image to "light" a radius and use the color mod on that and mod the colors from there...

**Comment by SpiceyWolf** [comment]
or ud have to just settle for making images for EVERY light + source u wanna use

**Comment by Raven-Quest** [comment]
well, I did try the change color on the light texture, but that seems to not work?

**Comment by SpiceyWolf** [comment]
what is the original color? and you change the color on the sprite for it in the application.

**Comment by Raven-Quest** [comment]
white, transparent ofcourse

and yes, I know, the sprite uses the texture, I was naming it wrong :P

**Comment by Raven-Quest** [comment]
but I also tried a black one, so reversed that did not work either

**Comment by Raven-Quest** [comment]
i don't need anything fancy, just a simple hue change would be fine xD

**Comment by SpiceyWolf** [comment]
yeah the colors only mod the original... white is the only color u can use that will be a visible change... but basicly

Dim newsprite as new SFML.Graphics.Sprite(TexturePathHere)
newsprite.color = SFML.Graphics.Color(R,G,B,A)

**Comment by Raven-Quest** [comment]
yeah, that's basicly what i tried i think

        'LightSprite.TextureRect = New IntRect(0, 0, LightSprite.Texture.Size.X, LightSprite.Texture.Size.Y)
        LightSprite.Color = New SFML.Graphics.Color(255, 0, 0, 255)
        ' 16 offset is for the center of the graphic
        LightSprite.Origin = New Vector2f(LightSprite.TextureRect.Width / 2 - 16, LightSprite.TextureRect.Height / 2 - 16)
        LightSprite.Position = New Vector2f(x2, y2)
        NightGfx.Draw(LightSprite, New RenderStates(BlendMode.Multiply))

**Comment by Raven-Quest** [comment]
![light](https://cloud.githubusercontent.com/assets/2353938/22939608/8bf806f6-f2df-11e6-87b5-fc3b1d442ce8.png)

and this is my current png

**Comment by SpiceyWolf** [comment]
try just color.red instead of (255,0,0,255)

**Comment by SpiceyWolf** [comment]
if it doesnt work, try opening it in gimp and changing the color balance to more of like a light gray(or at least light-ish)

**Comment by SpiceyWolf** [comment]
i didnt like how the color system worked in sfml, so in my q-bert game where i used it i just recolored the sprite in gimp and listed a new sprite everytime..

**Comment by Raven-Quest** [comment]
lol, that's also a way of doing it xD

**Comment by Raven-Quest** [comment]
'Create the light texture to multiply over the dark texture.
                        LightSprite.Position = New Vector2f(X1, Y1)
                        LightSprite.Color = New SFML.Graphics.Color(SFML.Graphics.Color.Red)
                        NightGfx.Draw(LightSprite, New RenderStates(BlendMode.Multiply))

no red to see anywhere lolz

**Comment by SpiceyWolf** [comment]
btw the C# engine i was working has been canceled... cause i realized i could do it WAAAAAAAY faster in D XD

**Comment by Raven-Quest** [comment]
lol wtf dude... xD

**Comment by SpiceyWolf** [comment]
nono dont make it new color
just color = color.red

**Comment by SpiceyWolf** [comment]
u can try making the light source a light blue, idk u gotta try modding the actual image with the red code first until something works then youll know what specificly the image template has to be... thats what i did
color.red WILL work when the image is proper then u can modify the values that way..

**Comment by Raven-Quest** [comment]
nope, still white xD

**Comment by SpiceyWolf** [comment]
yeah try changing ur lightsource image color to like a light blue or something and try it again

**Comment by Raven-Quest** [comment]
ok, ill try

**Comment by Raven-Quest** [comment]
it just stays white wtf... lolol

**Comment by SpiceyWolf** [comment]
boii...

**Comment by SpiceyWolf** [comment]
i told you CHANGE THE LITERAL PICTURES COLOR
not with code... with an actual image program and try... it cant stay white if the actual image itself ISNT WHITE

**Comment by Raven-Quest** [comment]
i know...
i did xD

**Comment by SpiceyWolf** [comment]
if u did then how is the picture "still white"?

**Comment by Raven-Quest** [comment]
exactly...

**Comment by SpiceyWolf** [comment]
then u didnt do it! it doesnt just render all ur sprites and tilesets as pure white does it?

**Comment by Raven-Quest** [comment]
ill try different editor

**Comment by Raven-Quest** [comment]
no ofcourse not 
i have no clue wtf is wrong with this piece of shit, ill try a diff gfx prog

**Comment by SpiceyWolf** [comment]
cuz if it doesnt ur doin it wrong... sprite.color does not mod stuff to become white... the .white value makes it native color of the image... change the physical image... put it in ur app... run sprite.color = color.red and if the color remains (whatever u changed the png color to, NOT WHITE) then its not working on code end

**Comment by SpiceyWolf** [comment]
but if its white then u didnt mod the image

**Comment by Raven-Quest** [comment]
http://www.ascensiongamedev.com/resources/filehost/fd52c5942312fb5ea877d2f194997301.png

I'm fucking stumped O.o

**Comment by SpiceyWolf** [comment]
lmfao u made the wrong part blue the shit that was white was supposed to be blue, the shit that was transparent is supposed to still be transparent

**Comment by Raven-Quest** [comment]
oh my god xD

**Comment by Raven-Quest** [comment]
well, that would explain a lot LOL

**Comment by Raven-Quest** [comment]
would something like this work?

http://www.pngall.com/light-png

**Comment by SpiceyWolf** [comment]
http://www.pngall.com/wp-content/uploads/2016/06/Light-PNG-HD.png

That is specificly what i was tellin you to do to urs

**Comment by Raven-Quest** [comment]
somewhere, something is very very fucked up lolz

http://www.ascensiongamedev.com/resources/filehost/e28ee3a4216ee4cd1f0ac3107d0cd786.png

**Comment by Raven-Quest** [comment]
and yes, that's the exact image from that site

**Comment by SpiceyWolf** [comment]
its cause ur blend mode... dont use multiply... it takes the color that is already there (in ur case the dark) and multiplies its alpha by the alpha of the picture of the specified image.

**Comment by SpiceyWolf** [comment]
alpha of the pixel location in said image i should say...

**Comment by Raven-Quest** [comment]
this is blendmode add
http://www.ascensiongamedev.com/resources/filehost/755c1aa6609d10debc0ff9684a450435.png

and this with blendmode alpha, 
http://www.ascensiongamedev.com/resources/filehost/755c1aa6609d10debc0ff9684a450435.png

that's all I got O.o

**Comment by SpiceyWolf** [comment]
in THAT case if u are gunna use alpha to make the shit lighter in that location... rather than transpose a color over a dark area and it still be dark just in that color xD
ull need to draw 2 images...
one where its multiplied like the original light source image you had...
and one where its "blendmode.add" with the color
this way theres a light area in JUST the right place with the right depth... but then it mods the colors of what itsnt darkened of just that area..

**Comment by Raven-Quest** [comment]
wut? now you lost me xD

god what have I done :P

**Comment by SpiceyWolf** [comment]
Okay heres what you do.

**Comment by SpiceyWolf** [comment]
you had this originally:

'Create the light texture to multiply over the dark texture.
LightSprite.Position = New Vector2f(X1, Y1)
LightSprite.Color = New SFML.Graphics.Color(SFML.Graphics.Color.Red)
NightGfx.Draw(LightSprite, New RenderStates(BlendMode.Multiply))

**Comment by Raven-Quest** [comment]
yes

**Comment by SpiceyWolf** [comment]
you will need to basicly create 2 light sprites... but have these names:

LightColorSprite
LightAreaSprite

**Comment by SpiceyWolf** [comment]
LightColorSprite should load the texture that you ORIGINALLY had for the light texture (where it was transparent background and the white circle in the middle)

**Comment by SpiceyWolf** [comment]
LightAreaSprite should load the texture you had with the blue background with the white circle in the middle

**Comment by SpiceyWolf** [comment]
Now when you get to this draw code you specified here: (Again this is original)

'Create the light texture to multiply over the dark texture.
LightSprite.Position = New Vector2f(X1, Y1)
LightSprite.Color = New SFML.Graphics.Color(SFML.Graphics.Color.Red)
NightGfx.Draw(LightSprite, New RenderStates(BlendMode.Multiply))

**Comment by SpiceyWolf** [comment]
Youll wanna change it to this...

'Create the light texture to multiply over the dark texture.
LightColorSprite.Position = LightAreaSprite.Position = New Vector2f(X1, Y1)
LightColorSprite.Color = LightAreaSprite.Position = New SFML.Graphics.Color(SFML.Graphics.Color.Red)
NightGfx.Draw(LightAreaSprite, New RenderStates(BlendMode.Multiply))
NightGfx.Draw(LightColorSprite)

**Comment by Raven-Quest** [comment]
ok, let me try that

**Comment by SpiceyWolf** [comment]
then youll have the area brightened up in just the middle like you did before...
and then the LightColorSprite will mod the color of that area there... if the lightcolor looks weird in there... then well just try different blend modes on it till it works..

**Comment by Raven-Quest** [comment]
kk, ill toy with that :)

**Comment by SpiceyWolf** [comment]
Damian... need to know if you currently have something you been working on... (that hasnt been uploaded yet) was about to start doing some work cleaning up and "trying" to semi-transition the network...

**Comment by Raven-Quest** [comment]
no, your good to go mate :)

**Comment by SpiceyWolf** [comment]
Closin this since we dont need this giant ass block of text no more xD
