### ISSUE TITLE
SFML lol

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#19]
:DELETED:

**Comment by Raven-Quest** [comment]
kk :)

**Comment by SpiceyWolf** [comment]
Aight so almost done downloading all the versions of sfml i needed again, the gtk# dlls will be removed from the internal and reposted within the hour :D

**Comment by SpiceyWolf** [comment]
Im also gunna change the target version in orion and repost that before i do other changes... just to kickstart some updates :D

**Comment by Raven-Quest** [comment]
Cool 😊

**Comment by SpiceyWolf** [comment]
Hey damian666, any chance we can get the "data" resources ported out to a separate repo like dropbox or some shit? its annoying trying to port the resources every time i need to reclone when im just going to throw them out again >_> Not to mention i have a few people one of them apperently in contact with you that wouldnt be using them its just kinda pointless to have everyone redownloading them to have em pop in their own resources... like you could keep them on a website like : For free gfx go here, for Music go here, for ... go here.

**Comment by Raven-Quest** [comment]
that's gonna end ugly man, people already struggle getting it to work xD

just ignore the data files then?

**Comment by SpiceyWolf** [comment]
Aight ima fork u pull from there then… I delete this shit and start over about 10 times a day when I work on it and it’s a pain downloading about 40mb of extra garbage data.

**Comment by Raven-Quest** [comment]
fine by me man :)

**Comment by SpiceyWolf** [comment]
already uploaded the sfml change tho

**Comment by Raven-Quest** [comment]
oh nice, got it :)

**Comment by SpiceyWolf** [comment]
Im lookin to update the archaicio libs with the version i have with encryption and stuff, as well pop in network soon..

**Comment by SpiceyWolf** [comment]
Encryption would protect data theives so people dont get hacked also..

**Comment by SpiceyWolf** [comment]
protect from* lol

**Comment by Raven-Quest** [comment]
great :)

I love that ^.^

**Comment by SpiceyWolf** [comment]
Ima close this since issue has been technically fixed ;P Open a new one if u need to tell me sometin.
