### ISSUE TITLE
Pet System

### ISSUE THREAD

**Issue by ZenfadeCOM** [Damian666/Orion-Plus-Game-Engine#28]
Everytime i try to spawn a pet it crashes the client.

**Comment by Raven-Quest** [comment]
ill check :)

**Comment by Raven-Quest** [comment]
may I ask how you get it to error?

precise steps?

**Comment by ZenfadeCOM** [comment]
Wait you guys still working on the engine? :)

**Comment by Raven-Quest** [comment]
why ofcourse :)

**Comment by SpiceyWolf** [comment]
Damian... this engine is such a pain in the ass to convert the network... simple chit keeps breaking constantly without rewriting loads of shit that doesnt even have to do with networking like the game objects just cause they are passed through the network...

break constantly for the dumbest reasons and well bug checking only tells me network broke so i cant convert it without redoing half the engine... sorry man isnt going to happen.
