### ISSUE TITLE
Features!!

### ISSUE THREAD

**Issue by SSDDX-Devs** [Damian666/Orion-Plus-Game-Engine#31]
Hey Damian You are doing great
But i want to ask a question 
Are these features available in the engine?
-------------------------------------------------------------------------------------------------------------------
Right click menu on player to enable trade, guild and party
Moving Panoramas
Guild system
Bank system
Woodcutting, mining, fishing, crafting and alchemy
Style slash that will display when player attacks.
RPG ace NPC conversation
Shout Entire game if you kill a BOSS monster
Wings
-------------------------------------------------------------------------------------------------------------------

**Comment by Raven-Quest** [comment]
some yes, some no.

just try it and check it out :P
