### ISSUE TITLE
Server crash (again)

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#36]
9/4/2017 2:51:27 AM
System.NullReferenceException(0x80004003): Object reference not set to an instance of an object.
   at OrionServer.ServerPlayers.GetPlayerName(Int32 Index) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\Objects\ServerPlayers.vb:line 868
   at OrionServer.ServerPlayers.LeftGame(Int32 Index) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\Objects\ServerPlayers.vb:line 2929
   at OrionServer.ServerGeneral.DestroyServer() in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerGeneral.vb:line 286
   at OrionServer.ServerGeneral.ConsoleEventCallback(Int32 eventType) in D:\Orion-Plus-Game-Engine-master\Source\Server\Source\Modules\ServerGeneral.vb:line 258
Line:868 Filename: ServerPlayers.vb
Line:2929 Filename: ServerPlayers.vb
Line:286 Filename: ServerGeneral.vb
Line:258 Filename: ServerGeneral.vb

Was trying to edit Skills, Classes and some other shit, tried to start client up, it didn't.. then server crashed.

> Recieved CMSG: CCheckPing
> Recieved CMSG: CRequestSkills
> Sent SMSG: SUpdateSkill
> Recieved CMSG: CCheckPing
> Recieved EMSG: RequestEditSkill
> Sent SMSG: SSkillEditor
> Recieved CMSG: CCheckPing
> Recieved EMSG: SaveSkill
> Sent SMSG: SUpdateSkill To All
> Sent SMSG: SNews
> Sent SMSG: STotalOnline To All
> Sent SMSG: SNews
> Recieved CMSG: CCheckPing
> Recieved CMSG: CLogin
> Sent SMSG: SLoginOk
> Recieved CMSG: CCheckPing
> Recieved CMSG: CRequestClasses
> Sent SMSG: SClassesData
> Recieved CMSG: CCheckPing
> Recieved CMSG: CUseChar
> Sent SMSG: SGlobalMsg
> Sent SMSG: SLoadCharOk
> Sent SMSG: STotalOnline
> Sent SMSG: SGameData
> Sent SMSG: SPlayerInv
> Sent SMSG: SPlayerWornEq
> Sent SMSG: SMapWornEq
> Sent SMSG: SPlayerHp
> Sent SMSG: SPlayerMp
> Sent SMSG: SPlayerSp
> Sent SMSG: SPlayerEXP
> Sent SMSG: SMapNames
> Sent SMSG: SHotbar
> Sent SMSG: SSkills
> Sent SMSG: SPlayerStats
> Sent SMSG: SPlayerData
> Sent SMSG: SResourcesCahce
> Sent SMSG: STotalOnline To All
> Sent SMSG: STarget
> Sent SMSG: SPlayerXY
> Sent SMSG: SPlayerMsg
> Sent SMSG: SPlayerMsg
> Sent SMSG: SInGame
> Recieved CMSG: CCheckPing
> Recieved CMSG: CNeedMap
> Sent SMSG: SMapData
> Sent SMSG: SPlayerData
> Recieved CMSG: CCheckPing
> Recieved CMSG: CQuit
> Sent SMSG: STotalOnline To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All
> Sent SMSG: SMapItemData To All

Packets Sent and Recv before crash if it helps any.

**Comment by Raven-Quest** [comment]
replication steps would certainly help mate :)

**Comment by Raven-Quest** [comment]
a fluke it is then :)
