### ISSUE TITLE
Editor Not Connecting

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#37]
I moved the server to a VPS, and now the editor won't connect.. it's trying to connect to localhost, but in the client config xml file, the IP points to my VPS, and it connects just fine, but not the editor.

**Comment by Krilliac** [comment]
Also, when i connect, i'm on the wrong map (Which isn't even suppose to exist)

http://prntscr.com/gh8zzo

100 maps, and i get spawned on 101, while on Local, it spawns me on the correct map.

**Comment by Krilliac** [comment]
Tried to reproduce it with new chars and some other existing accounts and couldn't reproduce it, so maybe it was just a rare fluke or something, not sure.

**Comment by Raven-Quest** [comment]
101? that's a instance map O.o

**Comment by Krilliac** [comment]
Hmm, i had set it to instance, then set it back after i couldn't edit the map.. but what ever, all good now lol

**Comment by Krilliac** [comment]
Did some digging and found that the editor has its own config

https://github.com/Damian666/Orion-Plus-Game-Engine/blob/master/Source/Editors/Source/Modules/EditorLoop.vb#L149

but this config is NOT created when the editor is started up and defaults to the localhost, changing the hard coded address to my VPS (where the server is located) allows me to connect.

**Comment by Raven-Quest** [comment]
weird, that should point at the same file as the client.

same path, and editor should be run from within client folder O.o

**Comment by Krilliac** [comment]
Yeah tried that, didn't work.. there is also some differences in what is contained in the configs for client and editor.

**Comment by Raven-Quest** [comment]
the difference should not matter, all editor should take it login and ip/port

**Comment by ParchmentWolf** [comment]
Krillic has this issue been resolved on your end?

**Comment by Krilliac** [comment]
Nope, config not created/used at all.. just resorted to hardcoding the ip tell it's fixed

**Comment by ParchmentWolf** [comment]
this is an editor end issue?

**Comment by ParchmentWolf** [comment]
I just checked the editor, it does in fact have the code to load the options and that IS in fact used, it just doesnt save a file if one wasnt found. The exact directory its going to look is Where the Editor.exe is located, inside of a "Data" folder and the file it looks for inside there is called "Config.xml"

**Comment by ParchmentWolf** [comment]
If it isnt loading certain data from the xml (if it is actually in that location and found) then the categories the variables are listed in may be correct

Username, Password, SavePass are all under UserInfo
Ip, Port are under Connections
MenuMusic. Music, Sound, Volume are under Sfx

**Comment by ParchmentWolf** [comment]
These are the default values when the config is not found:

Options.Password = ""
            Options.SavePass = False
            Options.Username = ""
            Options.IP = "Localhost"
            Options.Port = 7001
            Options.MenuMusic = ""
            Options.Music = 1
            Options.Sound = 1
            Options.Volume = 100

**Comment by ParchmentWolf** [comment]
If you are still having trouble with connection via the settings it may be an issue of Localhost not being recognized and you can try 127.0.0.1

Aside there is nothing to be fixed so im going to assume this has been a settled issue or misunderstanding.
