### ISSUE TITLE
How do i open the event editor in client?

### ISSUE THREAD

**Issue by Krilliac** [Damian666/Orion-Plus-Game-Engine#41]
Been looking for the key in client but i have no idea where it is.. i only found out about it because i saw the the Editor Events form in client

**Comment by Raven-Quest** [comment]
there is no key...

open map editor, switch to events tab, click on map :P

**Comment by Krilliac** [comment]
Aaah now i see.. but what about the Editor? There isn't a form for it, not even an outgoing packet. 0_0

**Comment by Raven-Quest** [comment]
same way, and there is a form... xD

**Comment by ParchmentWolf** [comment]
Krilliac, Event data is apart of the map system in this engine, it isnt designed as a separate entity. As far as individual features of the event editor if you are struggling with those youll have to be more specific.
