### ISSUE TITLE
Not an issue, just questions

### ISSUE THREAD

**Issue by lokize** [Damian666/Orion-Plus-Game-Engine#45]
Hi, first, thanks for good work, I would like to know how you usually launch the updates and if you have a release deadline between them? Does orion have a PVP system? Is there any way to put fullscreen in my game? possible bug, map tool in "insert" key dont work for me...

**Comment by Raven-Quest** [comment]
updates? nah, its basically bug fixing now.
ofcourse there is pvp :)
and yes, we moved the map editor out of the client, that's in editor now

**Comment by lokize** [comment]
Thanks for reply, where can I download the current system build? because the one I downloaded the editor is out but I can not open it because it says it must be done inside the client and the client pressing insert it does not open!

**Comment by Raven-Quest** [comment]
nonono xd

you did not understand that right, put the editor.exe inside the client folder, then it works.

**Comment by lokize** [comment]
ahhh, just editor? another question how to fullscreen my client?

**Comment by Raven-Quest** [comment]
it only has a few resolutions, not fullscreen

**Comment by lokize** [comment]
Thanks, Is there no way to play in fullscreen? :(

**Comment by Raven-Quest** [comment]
code it in I guess?

**Comment by lokize** [comment]
Thanks for replys! Great Work!

**Comment by lokize** [comment]
Last question i think, sorry, any way to drop items in inventory or bag in death pvp / mode? Only code it?

**Comment by Raven-Quest** [comment]
yep, that's why its open source, so you can add it :)

**Comment by lokize** [comment]
Hi, I noticed that it was updated here 3 days ago but in the official engine topic the release is from July 22nd, how to download the latest version of the build?

**Comment by ParchmentWolf** [comment]
Just download it from github and compile with visual studio. If you have a issue with visual studio because of space limitations on your machine or installation problems then sharpdevelop(~50 mb) should be capable of opening orion and compiling it

**Comment by ParchmentWolf** [comment]
If you arent familiar with programming or vb.net in particular you will want to look into finding a programmer friend (its a requirement for customizing and expanding on the engine source.)
