### ISSUE TITLE
Compile client for android.

### ISSUE THREAD

**Issue by nowsfeky** [Damian666/Orion-Plus-Game-Engine#47]
Hello, Damian.
I would like to know if it is possible to use Basic4android (B4A) to compile the client for android?

**Comment by Raven-Quest** [comment]
no man, thats impossible...
its not the same code.

**Comment by ParchmentWolf** [comment]
@nowsfeky Orion is in VB.Net. B4A is a Java based VB6-ish clone language. Not to mention, Orion is using alot of windows specific stuff right now so even if compiling for android was possible in VB.net right now, it still would not work without removing the Windows exclusive dependancies.
