### ISSUE TITLE
ASFW Update

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#48]
Yo, I did update the ASFW again and downgraded it to .net 4.5 since the .Net standard stuff isnt really stable on feature vs .net version compatibility.

This update added some Async IO functions, as well as it gave a lot of bug fixes to the network.

Current bugs were that ability to create dead sockets past the player-limit as well as ddos via mass generation of sockets passed the player-limit (Since the limit will waste time killing the sockets made passed that point and re-open the listener), packet crashing, and HighIndex breaking (Which usage could crash the server because you tried to do anything against a non existent value past our player array size)

These have been fixed, but it came at a cost where you have to change when/where the startIndex is set on the listener. You should change it so that immediately after the socket = new Server(ClientPacket.Count, MAX_PLAYERS) to have socket.MinimumIndex = 1 and remove the 1 from the last param of StartListening function.

As well in the socket = new Server(ClientPacket.Count, MAX_PLAYERS) you want to put 0 between the ClientPacket.Count and MAX_PLAYERS as i added there a new PacketSize parameter... if you want to make use of that to optimize your packets by the way, when you declare new Client or Server, in InitializeNetwork, you can change them to:

Socket = new Client(ServerPacket.Count, 4096)

and

Socket = new Server(ClientPacket.Count, 4096, MAX_PLAYERS)

that packetsize parameter i added is so you can set your own size for the packets as myne staticly used 8192 before, but if you have many tiny packets (Which you do) its just not efficient to use such a large number for packet sizes... Orion originally used that smaller number, so that way above you can set it back down again :)

**Comment by Raven-Quest** [comment]
ok, I added the updated file, and the fixes you said it needed.
but client sees server is online, but server wont see it, thus not calling the Socket_ConnectionReceived sub

so its basically blind for the client xD

**Comment by Raven-Quest** [comment]
so I checked why it did not call the sub, when trying stuff, I got this message

http://www.ascensiongamedev.com/resources/filehost/48389dbe83d9f860ed5bcab26794aa1c.png

I checked the declaration of the socket, and it uses withevents, so I dunno why it complains about that :/

declaration
"Public WithEvents Socket As Server"

**Comment by Raven-Quest** [comment]
yea, I upgraded the server to 4.5 already :)
still the same though

**Comment by SpiceyWolf** [comment]
o.0 i have an example project that i used to test as i did these changes and it doesnt have problems firing the events (in .net 4.5)

**Comment by SpiceyWolf** [comment]
hrm... well double check it does say that ur using 4.5 in the properties panel, if it does and doesnt work try restarting VS cause sometimes it bugs out

**Comment by Raven-Quest** [comment]
http://www.ascensiongamedev.com/resources/filehost/0d604ac1872725a34e3c861fe37ab967.png
im sure its 4.5 mate...

what can I say?

**Comment by Raven-Quest** [comment]
restarted, still the same im afraid.

**Comment by SpiceyWolf** [comment]
might try readding the nuget package from scratch if that doesnt work either

**Comment by SpiceyWolf** [comment]
cause i swear to u this problem isnt real xD I can send u the whole source code (And a VB.net version that STILL works with it) all in .net 4.5

**Comment by SpiceyWolf** [comment]
oya verify you arent trying to use the older .net standard version of the dll too xD the current version should be 2.0.0, the older 1.x version that used .net standard 2.0 wont work

**Comment by Raven-Quest** [comment]
yea im sure, I removed that reference, and only have the new one loaded.

removed and readded package did nothing either :/

**Comment by SpiceyWolf** [comment]
https://www.nuget.org/packages/CS-ASFW/2.0.0

if you need to look at the package info and use a command to manually install (If its not showing up for some reason)

**Comment by Raven-Quest** [comment]
nah, its found fine by nuget, just asfw and it finds it, version 2 installed

**Comment by SpiceyWolf** [comment]
is the git up to date? I can try downloading and porting it in, but i cant test it x-x just make sure it compiles

**Comment by Raven-Quest** [comment]
let me push it, then you can try it.

**Comment by Raven-Quest** [comment]
now its up to date.

**Comment by SpiceyWolf** [comment]
k

**Comment by ParchmentWolf** [comment]
Oh chit, i forgot to mention another nifty feature i added (I originally did before i tried to cleanup my initial post to make sure it was clear)

I added a new event feature to the server too :D

Its called AccessCheck and its params are both integers, first for client index, second for packet index...

The purpose of this was to make it so you could put Admin/Editor exclusive packets at the bottom of the client packets and have a simple check of:

If PacketID >= (First Admin Packet Name Here) && 
   (Some Level Beyond Player) > (Get Player Access Here) Then
       DisconnectPlayer(Index)
End If

This will make sure that before a packet handler is even accessed/invoked you can boot improper peoples off it :D a 1 HackingAttempt call catches all so to speak... The main benefit of this is you can safely move the editors back into the client and really downsize the projects complexity overall without worry that editors could be abused or bypassed... (The main reason i encouraged you to remove them in the first place was to ensure that players cant hack if you forget one of the MANY security checks in every single dev function/UI, this would be write once problem solved just make sure packets are ordered properly and you wont have a problem)

**Comment by Raven-Quest** [comment]
yea sorry, I tried that, but that's a no go, lots of errors I don't even understand xd

ill just wait till you get up and running, im sure that's the better thing to do :P

**Comment by SpiceyWolf** [comment]
lots of errors? Like what?

**Comment by Raven-Quest** [comment]
things in your solution, my vs does not like c files xD

**Comment by SpiceyWolf** [comment]
o.o C files? U meen C# or did it actually generate bonified .c files?

**Comment by Raven-Quest** [comment]
I ofcourse mean c# :P

its all the same shit for me lolol

**Comment by SpiceyWolf** [comment]
wot vs are you using that doesnt support anything in C# well before vb.net?!

**Comment by Raven-Quest** [comment]
vs 2017, I get all kinds of complaints about root namespace etc.

its probably because I don't know what the fuck I'm doing :P

**Comment by SpiceyWolf** [comment]
..? are you saying complaints cause your code practice is viewed as aweful by other people or complaints by IDE because of something being (clearly) not installed properly?

**Comment by Raven-Quest** [comment]
lmfao, both, but I was talking about the ide haha

I don't give a fuck what others say man xD

**Comment by SpiceyWolf** [comment]
uuuuh uve had issues with shit ive made in the past and having to revert back to older stuff before when ive tried moving to .net 4.5, u sure it isnt ur 4.5 install thats fcked up?

**Comment by Raven-Quest** [comment]
I dunno, ill try

**Comment by Raven-Quest** [comment]
yep, im sure, that's just fine

**Comment by SpiceyWolf** [comment]
k hold out i guess x-x

**Comment by Raven-Quest** [comment]
yea, think that's the wise thing to do :)

**Comment by SpiceyWolf** [comment]
if ur itching to do anything major u could work on re-porting the editor back to the client xD strippin down the unnecessary/duplicate code by ALOT

**Comment by SpiceyWolf** [comment]
if the ASFW update ends up being a issue with ur IDE alone btw ill help u get it reinstalled xD

**Comment by SpiceyWolf** [comment]
k my thing finally came in and i just installed windows but my net is still super slow so it may be a day or 2 till im totally setup and ready to do this.

**Comment by SpiceyWolf** [comment]
i just realized when us aid VS complaining about root namespaces...
ur probably refering to that shit where its like oh, u have it here in this folder called "xyz" but its not in a namespace called "xyz" and that warning is fekin annoying lol

**Comment by Raven-Quest** [comment]
that could very well be it, ill just hang tight, till you got time to check :)

**Comment by SpiceyWolf** [comment]
nvm it was part of a bug fix i did and i found the mistake -.- forgot to flip a sign from > to < >_<

**Comment by SpiceyWolf** [comment]
Welp, updating the nuget package now so when its up to date ill push the changes to the git and ull be runnin on the new lib file :D

**Comment by ParchmentWolf** [comment]
Youve posted some updates without a complaint so I take it were golden xD Feel free to close this anytime man :)

**Comment by Raven-Quest** [comment]
yep :)
