### ISSUE TITLE
Change request from me

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#49]
>.> I did this lol nvm

**Comment by SpiceyWolf** [comment]
Gud its settled... u move editors back in, ill do the cleanup and move you to MonoGame and no more buggy render problems :)

**Comment by SpiceyWolf** [comment]
ugh it became clear really fast that either some features are useless and literally doing nothing (But uve been managing them) or they have been bugged for a while and u werent sure how to fix them but they werent a huge deal (Still useless) cause after tryna remerge the editors its becoming clear that certain stuff had been overlapping with values in other editors where if they do anything at all they shouldnt be....

Quick example: EDITOR_PET = 7 and EDITOR_QUEST = 7. These are both setting the same variable upon use... the random separation of this stuff isnt exactly fixing any problems but risking creating problems.

**Comment by SpiceyWolf** [comment]
and we got issues of duplicate constants (Theyve been there... you either didnt bug because the constants have never been attempted to change anywhere or because u just werent using one of them... either way the merger is definitely causing use of both kinds and that can be a future headache)

**Comment by SpiceyWolf** [comment]
hory shet... yeh we needed to do something about your render style badly x-x having any other windows overlapping the game window it still registers clicks despite not actually clicking on it >_> also i got the editors put back in... idk to what degree they may be feked up tho concidering i havent done anything about the duplicate types with different casing or _ added that was different between client and editor on merge (Or existing prior TO)

**Comment by Raven-Quest** [comment]
yea, the separation was not a good thing xD

lost track very quickly im afraid :/

**Comment by SpiceyWolf** [comment]
*Sigh* ill move things back together and reorganize... itll be a bit of a pain at first but ill make sure to region the fek outta things (If/where necessary) and comment block others

**Comment by SpiceyWolf** [comment]
As a heads up, in the MonoGame transition, there is some optimization im doing to the render functions (As I have to redo them anyway) and as a part of doing so, some things like the paperdolls and character sprites needed to change format... so I made a tool to include with Orion+ for rearranging the sprite sheets into the new format :)

**Comment by SpiceyWolf** [comment]
x-x forgot we get zbuffering now... i can do some REALLY crazy performance + shit later xD

**Comment by SpiceyWolf** [comment]
jesus, dude try to remember this for later -> Using Goto should ONLY be used for errors not just general skipping (Unless its ABSOLUTELY unavoidable) especially in loops to force a next loop, use Continue.

**Comment by SpiceyWolf** [comment]
hory shet gross bug with trading... im fixing it so when ur trading itll still render the damn item (Just a grayed version) as well in ur trade it checks if ur giving a type of item in general and wont render anymore in inventory with that same item type (Example Money) so im fixing it to register a slot that is being used in a trade as well so we can disable JUST that specific one

**Comment by SpiceyWolf** [comment]
Nvm about the trade thing there was a bug but not how i thought it was... anyway still fixing the draw to do a gray for the one thats there rather then draw nothing at all..

**Comment by SpiceyWolf** [comment]
been fixing it up so it does the animated item frames for alot less performance cost xD (Map, Cursor, and Inventory) -- Its also drawing the Amount on the cursor now :D

**Comment by SpiceyWolf** [comment]
I think ull love how clean the new Item renderers are, ive been able to remove a few subs and reduce code dramatically :D (Bout to post the code into a sample page)

**Comment by SpiceyWolf** [comment]
[Sample Item Renderer.txt](https://github.com/Damian666/Orion-Plus-Game-Engine/files/2853152/Sample.Item.Renderer.txt)

**Comment by SpiceyWolf** [comment]
heads up -> I AM putting better render handles in for everything so stuff that is based off a portion of picX/Y where its 32 (literal picvals) 16(Half) and 8(Quarter) im replacing them with picX */ so picX will actually replace them and putting consistent error checks so u cant have a value set higher then maxval or less then 1(As most handlers only partially impliment the check or not at all) to make sure rendering is safe.

**Comment by SpiceyWolf** [comment]
Btw im giving orion a good light system as i redo that code xD

**Comment by SpiceyWolf** [comment]
k... so ive rewrote the revamp branch for now with the MonoGame version (Definitely incomplete atm lol) but i got it here so theres no chance i lose it again in case something happens >_> I dont trust windows at all

**Comment by SpiceyWolf** [comment]
because of a SUPER tiny issue with MonoGame not wanting to split graphics between multiple "Devices" and the workaround I came up with for Winforms, you DO lose performance when rendering to more (And bigger) surfaces... so im leaving in a switch method in here so for the literal gamerz that wont have access to the editors anyway (Which will be the only thing really affected end game here) itll use the game window as the only graphics device... but when a developer needs to come on, they can run the special version that uses my Winforms Graphics Device instead... itll run a bit slower then normal game but have working editors :D

(Honestly it just adds another layer of security against people breaking into editors tbh lol)

**Comment by SpiceyWolf** [comment]
ugh too many changes without a reliable way to test if MG bugs or its me -.- so im gunna push these changes i have so far into the SFML version (Do a cleanup thanks to my previous SFML work adding MG-Like handlers) and attempt the MG conversion later when its more suitable as is.... so im not overly backtracking just changing the code base for the improvements i was already making -> As well i am bringin in the Launcher again soon :D

**Comment by SpiceyWolf** [comment]
I had an idea for something different to do with the launcher too >.> Making a custom webs site and using the net browser control in .net to present it AS the form... so u can dynamically change the UI and host assets to download etc (Using similar method to what my launcher does to rip assets to begin with... just targetting the downloads section of the same site) as a good example for how people can easily use the launcher as a autoupdater (For free)

**Comment by SpiceyWolf** [comment]
oh yeah doing so would ALSO drastically reduce the download size for the git cause the launcher would be responsible for downloading the vanilla assets (Which we can change anytime with format changes etc) and ONLY have code on the git

**Comment by SpiceyWolf** [comment]
Fader just got an upgrade in performance as well reduced potential glitches from the old audio page setup (Should my code not have game crashing bugs that is) i also imported my infinite sound player (For general sounds ud play once then toss) so the ONLY extra sound player needed is for weathers so we can start/stop them dynamicly.. it could use some slight tweaking though if we wanna use distance based sound volumes (like rushing water).

**Comment by SpiceyWolf** [comment]
o i also pooped in the icons i promised u a while back :D and got that license changed up >: P

**Comment by SpiceyWolf** [comment]
>.< i hate having to update my nuget packages ;~;
I totally forgot about adding text rendering to my spritebatches

**Comment by SpiceyWolf** [comment]
x-x ok so hopefully... tomorrow i should have a working build with the Remodel... the biggest change is the fact ive cleaned up the daum graphics and audio modules... AND its all runnin SpriteBatch (Which saves the target its rendering to between each begin and end calls)

it does optimize the rendering if it happens to reuse the same texture for multiple draw calls in a row... like drawing the map if its MOSTLY 1 tileset say the ground... u reduce the draw time SIGNIFICANTLY because it actually just caches the draw call until its time to use a different texture then draws em all at once...

**Comment by Raven-Quest** [comment]
you busy mate xD

im working, so im not around :)

**Comment by SpiceyWolf** [comment]
yesh im busy af xD

**Comment by SpiceyWolf** [comment]
also lots of changes, im expecting LOADS of shit to break when people test it... to what degree i dunno... maybe sometimes its gunna say index overflow and maybe sometimes it wont but something wont draw or be processed cause the index was just 1 too short... i cant remember how to loop properly with vb.net cause its not consistent with how every other lang handles arrays and loop bounds -.- i cant remember in what way it differs so im just gunna have to let things not quite work properly and let people report where shit gets weird.

**Comment by SpiceyWolf** [comment]
they will be simple fixes ofc, but it will suck having to wait to find out what breaks where >_<

**Comment by SpiceyWolf** [comment]
ugh need to start testing some stuff before finish x-x so im just gunna make it work in place as much as i have converted now... then correct whatever is broken later (Give myself a chance to cleanup a bit slower then all at once)

**Comment by SpiceyWolf** [comment]
stuff is actually getting quite messy because of the need to rewrite the screens too... so im actually doing a smaller thing where i rebuild the engines (In source) just slowely ripping parts as i need em and fixing errors from changes as i go til the whole thing is back up x-x

On side news... the launcher works properly and i have the contents hosted >: P
I am also writing documentation for the engine (For navigation, usage and development) as i go. after i got a small version of the engine back and working ill post up a copy in the revamp, i havent deleted the source just moved everything to non-compile in OldSource so its all still there as i go :)

I think ud cry at the launcher man its beautiful :D

**Comment by SpiceyWolf** [comment]
on the server im reimplimenting the console as a controller where itll by default open a GUI, but if you use a batch to start it with a commandline (Console) or change the start properties in the windows/properties menu then itll boot as a cmd :D the 1 set of commands will be ported directly into the object being used too so no need for a million switches..
