### ISSUE TITLE
An update is required!

### ISSUE THREAD

**Issue by ParchmentWolf** [Damian666/Orion-Plus-Game-Engine#51]
Hi... So im still on my goals of transitioning to lower level stuff as I posted in my other issue post -> However out of respect of maintaining my library ASFW since people are using it for serious projects... I was notified earlier today about a big issue with mass connection and disconnection and in the process of fixing that issue found a few other important bug fixes and optimization potential.

Just wanted to suggest you should really update the ASFW to take advantage of those bug fixes (requires no actual code change)

And in the place of code where its checking against HighIndex, I have made an added function to return a list of just the currently used index's called ConnectionIds().

If say, there was at one point 100 connections, and only 3 people remain using the indexes in the 90's range, doing the highIndex loops will loop 0 to 95 or whatever that highest index value is... However, doing a foreach against ConnectionIds instead of the For 0 to HighIndex itll only actually loop 3 objects.

You would still want to do IsConnected checks as currently in place -- in case someone disconnects mid-loop, but this will severly optimize the checks wherever a games project may have had high traffic.

**Comment by ParchmentWolf** [comment]
Actually looking through here it seems orion does away with any meeningful places I knew eclipse to actually use High_Index (which could have benefited from that optimization) or it was based on a version of EO that never had high index... either way the thing im gunna push to my fork switches the ASFW version to my latest (and GOOD GOD i didnt realize you were on that old buggy version of asfw -> ASFW_CS). Required some mass code change to fix differences but its all good now :D

**Comment by Raven-Quest** [comment]
never had the highindex, so yea.

but hee, thanx bro :)
