### ISSUE TITLE
Editors Disconnect when saving

### ISSUE THREAD

**Issue by Chronos-92** [Damian666/Orion-Plus-Game-Engine#7]
For some reason whenever I save anything, the editors will tell me I have disconnected. It will then not always save everything I've changed (Items only saves the first item) and restarting the server causes a loss of almost all saved data from the editors.

**Comment by ParchmentWolf** [comment]
then packets arent being read the same as it was written... the packets in the current network expect you to reread the name out of it, then start the data, and reading more data than the packet contained or incorrect sizes between written/read can cause it to return an error which kicks back to the catch in the network data received function.

**Comment by Chronos-92** [comment]
In general yes, however this was related to my change in the login packets which I didn't see. The editor assumed you received data which I never paid attention to when I swapped around some packets and their names in https://github.com/Damian666/Orion-Plus-Game-Engine/commit/8a5e91966c0521650db1c9056b98e57055a63682

Damien has since fixed it and created a new packet for the editor in https://github.com/Damian666/Orion-Plus-Game-Engine/commit/32e5198a0be901c7b9eab6da3a62a969d467d1c4 so this issue is resolved.
